eureka:
    client:
        region: default
        registry-fetch-interval-seconds: 5
server:
    port: 8080
spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:  
            - id: ecg
              uri: localhost:8090
