eureka:
    client:
        region: default
        registry-fetch-interval-seconds: 5
server:
    port: 8080
spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:  
            - id: method_route
              uri: https://example.org
              predicates:
              - Method=GET,POST
